<?php
session_start();
require_once '../includes/auth.php';
requireRole('admin');
require_once '../config/db.php';

$user = getCurrentUser();

// Capital Recovered Data — remaining_balance pulled from loans, not repayments
$query = "SELECT 
    r.id,
    r.amount_paid,
    r.payment_date,
    r.payment_method,
    l.remaining_balance,
    l.id AS loan_id,
    u.full_name
FROM repayments r
JOIN loans l ON r.loan_id = l.id
JOIN users u ON l.borrower_id = u.id
ORDER BY r.payment_date DESC";

$result = $conn->query($query);

if (!$result) {
    die('Query failed: ' . $conn->error);
}

$totalQuery = "SELECT SUM(amount_paid) as grand_total FROM repayments";
$totalRow = $conn->query($totalQuery)->fetch_assoc();
$grandTotal = $totalRow['grand_total'] ?? 0;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>CapitalRecovered_<?php echo date('Ymd'); ?></title>
    <link rel="stylesheet" href="../assets/css/full_history_report.css">
</head>
<body>

<div class="no-print" style="text-align:center; margin-bottom:20px;">
    <button onclick="window.print()" style="padding:10px 20px; background:#27ae60; color:#fff; border:none; cursor:pointer; border-radius:5px; font-weight:bold;">PRINT CAPITAL RECOVERED REPORT</button>
    <a href="reports.php" style="margin-left:10px; color:#666;">Back to Dashboard</a>
</div>

<div class="statement-container">
    <div class="watermark">CAPITAL RECOVERED</div>

    <div class="header">
        <div>
            <h1 style="margin:0; color:var(--dark-slate);">MICRO<span>LOAN</span> SYSTEM</h1>
            <div style="color:#27ae60; font-weight:bold; font-size:12px;">CAPITAL RECOVERED REPORT</div>
        </div>
        <div style="text-align:right; font-size:12px;">
            <strong>Ref:</strong> AD-RECV-<?php echo date('Ymd'); ?><br>
            <strong>Generated:</strong> <?php echo date('d M Y, H:i'); ?><br>
            <strong>Admin:</strong> <?php echo htmlspecialchars($user['full_name']); ?>
        </div>
    </div>

    <div class="info-grid">
        <div class="info-box" style="grid-column: span 3;">
            <div style="font-size:10px; color:#27ae60; font-weight:bold;">TOTAL CAPITAL RECOVERED</div>
            <div style="font-size:22px; font-weight:bold; color:#27ae60;">KES <?php echo number_format($grandTotal, 2); ?></div>
        </div>
    </div>

    <table class="statement-table">
        <thead>
            <tr>
                <th>Payment Date</th>
                <th>Borrower</th>
                <th>Loan Ref</th>
                <th>Method</th>
                <th class="text-right">Amount Paid (KES)</th>
                <th class="text-right">Loan Rem. Balance</th>
            </tr>
        </thead>
        <tbody>
            <?php while($row = $result->fetch_assoc()): ?>
            <tr>
                <td><?php echo date('d M Y', strtotime($row['payment_date'])); ?></td>
                <td><strong><?php echo htmlspecialchars($row['full_name']); ?></strong></td>
                <td>#LN-<?php echo str_pad($row['loan_id'], 4, '0', STR_PAD_LEFT); ?></td>
                <td><small><?php echo strtoupper(str_replace('_', ' ', $row['payment_method'])); ?></small></td>
                <td class="text-right" style="color:#27ae60; font-weight:bold;">KES <?php echo number_format($row['amount_paid'], 2); ?></td>
                <td class="text-right">KES <?php echo number_format($row['remaining_balance'], 2); ?></td>
            </tr>
            <?php endwhile; ?>
        </tbody>
        <tfoot>
            <tr style="background:#f9f9f9; font-weight:bold;">
                <td colspan="4" style="text-align:right; padding:10px;">TOTAL RECOVERED</td>
                <td class="text-right" style="color:#27ae60;">KES <?php echo number_format($grandTotal, 2); ?></td>
                <td></td>
            </tr>
        </tfoot>
    </table>

    <div style="margin-top:50px; display:flex; justify-content:space-between; align-items:flex-end;">
        <div style="font-size:10px; color:#999;">
            GENERATED BY SYSTEM ADMIN<br>
            ID: <?php echo $user['id']; ?> | IP: <?php echo $_SERVER['REMOTE_ADDR']; ?><br>
            *** END OF RECOVERY RECORD ***
        </div>
        <div>
            <div style="font-family:'Brush Script MT',cursive; font-size:24px; margin-bottom:5px; color:var(--dark-slate); text-align:center;">
                <?php echo htmlspecialchars($user['full_name']); ?>
            </div>
            <div style="text-align:center; border-top:1px solid #000; width:220px; padding-top:10px; font-size:11px; text-transform:uppercase; letter-spacing:1px;">
                Authorized Admin Signature
            </div>
        </div>
    </div>
</div>

</body>
</html>