<?php
session_start();
require_once '../includes/auth.php';
requireRole('admin');
require_once '../config/db.php';

$user = getCurrentUser();

// Outstanding per loan: total_amount minus all repayments made
$query = "SELECT 
    l.id AS loan_id,
    l.total_amount,
    l.status,
    l.created_at,
    u.full_name,
    COALESCE(SUM(r.amount_paid), 0) AS total_paid,
    (l.total_amount - COALESCE(SUM(r.amount_paid), 0)) AS balance_outstanding
FROM loans l
JOIN users u ON l.borrower_id = u.id
LEFT JOIN repayments r ON r.loan_id = l.id
WHERE l.status IN ('approved', 'completed')
GROUP BY l.id, l.total_amount, l.status, l.created_at, u.full_name
HAVING balance_outstanding > 0
ORDER BY balance_outstanding DESC";

$result = $conn->query($query);

$summaryQuery = "SELECT 
    SUM(total_amount) as total_disbursed,
    (SELECT SUM(amount_paid) FROM repayments) as total_recovered
FROM loans WHERE status IN ('approved', 'completed')";
$summary = $conn->query($summaryQuery)->fetch_assoc();
$outstanding = ($summary['total_disbursed'] ?? 0) - ($summary['total_recovered'] ?? 0);
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Outstanding_<?php echo date('Ymd'); ?></title>
    <link rel="stylesheet" href="../assets/css/full_history_report.css">
</head>
<body>

<div class="no-print" style="text-align:center; margin-bottom:20px;">
    <button onclick="window.print()" style="padding:10px 20px; background:#c0392b; color:#fff; border:none; cursor:pointer; border-radius:5px; font-weight:bold;">PRINT OUTSTANDING BALANCES REPORT</button>
    <a href="reports.php" style="margin-left:10px; color:#666;">Back to Dashboard</a>
</div>

<div class="statement-container">
    <div class="watermark">OUTSTANDING RISK</div>

    <div class="header">
        <div>
            <h1 style="margin:0; color:var(--dark-slate);">MICRO<span>LOAN</span> SYSTEM</h1>
            <div style="color:#c0392b; font-weight:bold; font-size:12px;">OUTSTANDING BALANCES — RISK EXPOSURE REPORT</div>
        </div>
        <div style="text-align:right; font-size:12px;">
            <strong>Ref:</strong> AD-OUTST-<?php echo date('Ymd'); ?><br>
            <strong>Generated:</strong> <?php echo date('d M Y, H:i'); ?><br>
            <strong>Admin:</strong> <?php echo htmlspecialchars($user['full_name']); ?>
        </div>
    </div>

    <div class="info-grid">
        <div class="info-box" style="grid-column: span 3;">
            <div style="font-size:10px; color:#c0392b; font-weight:bold;">NET OUTSTANDING (RISK)</div>
            <div style="font-size:22px; font-weight:bold; color:#c0392b;">KES <?php echo number_format($outstanding, 2); ?></div>
        </div>
    </div>

    <table class="statement-table">
        <thead>
            <tr>
                <th>Date Issued</th>
                <th>Borrower</th>
                <th>Loan Ref</th>
                <th>Status</th>
                <th class="text-right">Loan Amount</th>
                <th class="text-right">Total Paid</th>
                <th class="text-right">Outstanding</th>
            </tr>
        </thead>
        <tbody>
            <?php 
            $rows = [];
            while($row = $result->fetch_assoc()) $rows[] = $row;
            if(count($rows) > 0):
                foreach($rows as $row): ?>
            <tr>
                <td><?php echo date('d M Y', strtotime($row['created_at'])); ?></td>
                <td><strong><?php echo htmlspecialchars($row['full_name']); ?></strong></td>
                <td>#LN-<?php echo str_pad($row['loan_id'], 4, '0', STR_PAD_LEFT); ?></td>
                <td><small><?php echo strtoupper($row['status']); ?></small></td>
                <td class="text-right">KES <?php echo number_format($row['total_amount'], 2); ?></td>
                <td class="text-right" style="color:#27ae60;">KES <?php echo number_format($row['total_paid'], 2); ?></td>
                <td class="text-right" style="color:#c0392b; font-weight:bold;">KES <?php echo number_format($row['balance_outstanding'], 2); ?></td>
            </tr>
            <?php endforeach;
            else: ?>
            <tr><td colspan="7" style="text-align:center; padding:40px; color:#999;">NO OUTSTANDING BALANCES FOUND.</td></tr>
            <?php endif; ?>
        </tbody>
        <tfoot>
            <tr style="background:#f9f9f9; font-weight:bold;">
                <td colspan="6" style="text-align:right; padding:10px;">TOTAL OUTSTANDING</td>
                <td class="text-right" style="color:#c0392b;">KES <?php echo number_format($outstanding, 2); ?></td>
            </tr>
        </tfoot>
    </table>

    <div style="margin-top:50px; display:flex; justify-content:space-between; align-items:flex-end;">
        <div style="font-size:10px; color:#999;">
            GENERATED BY SYSTEM ADMIN<br>
            ID: <?php echo $user['id']; ?> | IP: <?php echo $_SERVER['REMOTE_ADDR']; ?><br>
            *** END OF OUTSTANDING RISK RECORD ***
        </div>
        <div>
            <div style="font-family:'Brush Script MT',cursive; font-size:24px; margin-bottom:5px; color:var(--dark-slate); text-align:center;">
                <?php echo htmlspecialchars($user['full_name']); ?>
            </div>
            <div style="text-align:center; border-top:1px solid #000; width:220px; padding-top:10px; font-size:11px; text-transform:uppercase; letter-spacing:1px;">
                Authorized Admin Signature
            </div>
        </div>
    </div>
</div>

</body>
</html>